name: BarterShops
api-version: '1.21'
version: ${project.version}
description: Barter trading plugin with sign-based shop creation
author: Derek Schrishuhn
main: org.fourz.BarterShops.BarterShops
depend: [RVNKCore]
softdepend: [Vault, WorldGuard, GriefPrevention]

commands:
  shop:
    description: Main command for BarterShops plugin
    usage: /<command> [subcommand]
    aliases: [barter, shops]

permissions:
  bartershops.use:
    description: Allows interacting with shops as a customer
    default: false
  bartershops.create:
    description: Allows creating and configuring barter shops, and all player commands
    default: false
  bartershops.admin:
    description: Full admin access — bypasses all shop restrictions
    default: op
