name: BarterShops
api: '1.21'
version: 0.1.1
description: This is a simple Bukkit Plugin
author: Derek Schrishuhn
main: org.fourz.BarterShops.Main

commands:
  shop:
    description: Main command for BarterShops plugin
    usage: /<command> [subcommand]
    aliases: [barter, shops]

permissions:
  bartershops.list:
    description: Allows listing all shops
    default: true
  bartershops.nearby:
    description: Allows finding nearby shops
    default: true
  bartershops.reload:
    description: Allows reloading the plugin configuration
    default: op