name: BarterShops
api-version: '1.21'
version: ${project.version}
description: Barter trading plugin with sign-based shop creation
author: Derek Schrishuhn
main: org.fourz.BarterShops.BarterShops
softdepend: [RVNKCore]

commands:
  shop:
    description: Main command for BarterShops plugin
    usage: /<command> [subcommand]
    aliases: [barter, shops]

permissions:
  bartershops.list:
    description: Allows listing all shops
  bartershops.nearby:
    description: Allows finding nearby shops
  bartershops.reload:
    description: Allows reloading the plugin configuration
    default: op