package org.fourz.BarterShops.data.dto;

import java.sql.Timestamp;
import java.util.Objects;
import java.util.UUID;

/**
 * Data Transfer Object for shop ratings using Java Record.
 * Immutable and thread-safe for cross-plugin data transfer via RVNKCore.
 *
 * <p>Represents a player's rating and review of a shop for reputation tracking.</p>
 */
public record RatingDataDTO(
    int ratingId,
    int shopId,
    UUID raterUuid,
    int rating,
    String review,
    Timestamp createdAt
) {
    /**
     * Compact constructor with validation.
     */
    public RatingDataDTO {
        Objects.requireNonNull(raterUuid, "raterUuid cannot be null");

        if (rating < 1 || rating > 5) {
            throw new IllegalArgumentException("rating must be between 1 and 5");
        }

        if (createdAt == null) {
            createdAt = new Timestamp(System.currentTimeMillis());
        }
    }

    /**
     * Creates a new rating without an ID (for insertion).
     *
     * @param shopId The shop being rated
     * @param raterUuid The UUID of the player rating
     * @param rating The star rating (1-5)
     * @param review Optional written review
     * @return A new RatingDataDTO
     */
    public static RatingDataDTO create(int shopId, UUID raterUuid, int rating, String review) {
        return new RatingDataDTO(
            0, // Will be generated by database
            shopId,
            raterUuid,
            rating,
            review,
            new Timestamp(System.currentTimeMillis())
        );
    }

    /**
     * Checks if this rating has a written review.
     *
     * @return true if review is not null and not empty
     */
    public boolean hasReview() {
        return review != null && !review.trim().isEmpty();
    }

    /**
     * Gets a truncated review for display.
     *
     * @param maxLength Maximum length of the review
     * @return Truncated review with ellipsis if needed
     */
    public String getTruncatedReview(int maxLength) {
        if (!hasReview()) {
            return "";
        }

        if (review.length() <= maxLength) {
            return review;
        }

        return review.substring(0, maxLength - 3) + "...";
    }

    /**
     * Gets the timestamp as epoch milliseconds.
     *
     * @return Timestamp in milliseconds since epoch
     */
    public long getTimestamp() {
        return createdAt != null ? createdAt.getTime() : 0;
    }

    /**
     * Builder for constructing RatingDataDTO with optional fields.
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Builder class for RatingDataDTO.
     */
    public static class Builder {
        private int ratingId = 0;
        private int shopId;
        private UUID raterUuid;
        private int rating;
        private String review;
        private Timestamp createdAt = new Timestamp(System.currentTimeMillis());

        public Builder ratingId(int ratingId) {
            this.ratingId = ratingId;
            return this;
        }

        public Builder shopId(int shopId) {
            this.shopId = shopId;
            return this;
        }

        public Builder raterUuid(UUID raterUuid) {
            this.raterUuid = raterUuid;
            return this;
        }

        public Builder rating(int rating) {
            this.rating = rating;
            return this;
        }

        public Builder review(String review) {
            this.review = review;
            return this;
        }

        public Builder createdAt(Timestamp createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        public RatingDataDTO build() {
            return new RatingDataDTO(
                ratingId, shopId, raterUuid, rating, review, createdAt
            );
        }
    }
}
